#!/bin/sh
# profile.gadunix
# Alpine mkimage profile for Gadunix
# Place this (and genapkovl.sh) in aports/scripts/ and run mkimage.sh with --profile gadunix
#
# Usage (from inside an Alpine build environment):
#   sh mkimage.sh --profile gadunix --arch x86_64 --outdir ~/iso

profile_gadunix() {
	profile_base  # inherit base profile defaults

	title="Gadunix"
	desc="A minimal general-purpose Linux"
	image_ext="iso"
	output_format="iso"
	arch="x86_64"
	profile_abbrev="gadunix"
	image_name="gadunix"

	# ── Kernel ─────────────────────────────────────────────────────────
	kernel_flavors="lts"          # linux-lts: stable, widely supported
	kernel_cmdline="quiet"

	# ── Init system ────────────────────────────────────────────────────
	# Alpine uses OpenRC by default — lighter than systemd, perfectly capable
	initfs_features="ata base cdrom ext4 keymap nvme raid scsi usb virtio"

	# ── Hostname / overlay ─────────────────────────────────────────────
	# apkovl is generated by genapkovl.sh and applied to the live system at boot.
	hostname="gadunix"
	apkovl="genapkovl.sh"

	# ── Packages baked into the ISO ────────────────────────────────────
	# These are installed into the live ISO image itself.
	# Anything not listed here can still be installed post-boot via apk.
	# Note: package repositories are passed to mkimage.sh via --repository flags.
	apks="
		alpine-base
		alpine-conf
		linux-lts
		linux-firmware-none
		grub-efi
		grub-bios
		efibootmgr

		busybox
		bash
		openssl
		ca-certificates
		curl
		wget

		openssh
		dropbear

		e2fsprogs
		dosfstools
		parted
		util-linux

		iproute2
		dhcpcd

		nano
		htop
		less
		mandoc
		man-pages

		git
		python3
		py3-pip

		gadunix-base
	"

	build() {
		build_iso
	}
}

# Override the base kernel section so the ISO pulls linux-firmware-none
# (empty) instead of the full linux-firmware meta-package, which is the
# single largest consumer of disk space during the build.
section_kernels() {
	local _f _a _pkgs
	for _f in $kernel_flavors; do
		_pkgs="linux-$_f linux-firmware-none wireless-regdb $modloop_addons"
		for _a in $kernel_addons; do
			_pkgs="$_pkgs $_a-$_f"
		done
		local id=$( (echo "$initfs_features::$_hostkeys" ; apk fetch --root "$APKROOT" --simulate alpine-base $_pkgs | sort) | checksum)
		build_section kernel $ARCH $_f $id $_pkgs
	done
}
